//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvatoMarketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int rwid { get; set; }
        public int pid { get; set; }
        public string comment { get; set; }
        public int rating { get; set; }
        public int uid { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
